#!/bin/bash

BASEDIR=${BASEDIR-/home/malc/astro/saser}

dirname_from_objname() {
  if echo $1 | egrep -iq '^HD66811\s*$' ; then 
    echo zet_pup 
    return
  fi 
   
  if echo $1 | egrep -iq '^zeta? pup(pis)?\s*$' ; then 
    echo zet_pup 
    return
  fi 
   
  if echo $1 | egrep -iq '^HD68273\s*$' ; then 
    echo 'gamma-2_vel' 
    return
  fi 
   
  if echo $1 | egrep -iq '^gam(ma)?\s*2?\s*vel(orum)?\s*$' ; then 
    echo 'gamma-2_vel' 
    return
  fi

  if echo $1 | egrep -iq '^HD143999\s*$' ; then
    echo 'u_tra'
    return
  fi

  if echo $1 | egrep -iq '^u\stra\s*$' ; then
    echo 'u_tra'
    return
  fi

  if echo $1 | egrep -iq '^HD139966\s*$' ; then
    echo 'hh_nor'
    return
  fi

  if echo $1 | egrep -iq '^hh\snor\s*$' ; then
    echo 'hh_nor'
    return
  fi
}

process_spectrum() {
  filename=$1
  objname=$2
  observer=$3

  echo "filename='$filename'"
  echo "objname='$objname'"
  echo "observer='$observer'"

  dirname=$(dirname_from_objname "$objname")
  if [ -z "$dirname" ] ; then
    printf "FATAL: %s: Unable to determine dirname from OBJNAME %s" $filename $objname
    exit 1
  fi
  echo $dirname
  
  basename=`basename $filename`
  mv -v $filename $BASEDIR/site/$dirname/fits/$basename
  echo "${dirname//_/ } from $observer"
}

set -e

count=0

while read line ; do
  filename=`echo -e "$line" | cut -f 1`
  objname=`echo -e "$line" | cut -f 2`
  observer=`echo -e "$line" | cut -f 3`
  date=`echo -e "$line" | cut -f 4  | cut -d T -f 1`
  process_spectrum "$filename" "$objname" "$observer"
  count=$(($count+1))
done < <(dfits $@ | fitsort -d OBJNAME OBSERVER DATE-OBS)

make
git add site/
git commit -v -m "${objname} from ${observer} ${date}" -e
